//LEARNT ABOUT VIRTUAL BASEE CLASS IN THEORY REFER IMAGE FOR CONCEPT
/*THE VIRTUAL BASE CLASS CAN BE EXPLAINED FROM EXMAPLE JUST LIKE IN TUT42 AND 43 IT IS 
RELATED TO THE AMBIGUITY IN INHERITANCE . CONSIDER A CLASS A WHICH IS INHERITED BY CLASS 
B AND C ,SUPPOSE THE CLASS A HAS A VARIABLE INT VAR .NOW THERE IS A NEW CLASS D WHICH IS 
MADE BY INHERITING THE CLASS B AND C ,NOW WHEN WE INHERITED CLASS A FOR B AND C WE INHERITED
THE INT VAR IN BOTH MEANING BOTH HAVE A INT VAR ,NOW IF WE USE THAT INT VAR IN CLASS D THEN
IT WILL GET CONFUSED THAT WHICH INT VAR SHOULD I USE?? (INT VAR WILL BECOME AMBIGIOUS) 
--------------------------------------------------------------------------------------------
SO TO AVOID THIS WE USE THE VIRTUAL BASE CLASS IN THAT WHAT HAPPENS IS THE B AND C CLASS
INHERIT A SUCH THAT ONLY 1 OF THE INT VAR WILL BE PASSED TO THE INHERITED NEXT CLASS (D IN 
OUR CASE) SYNTAX FOR INHERITING THE VIRTUAL CLASS A IS 
class B : virtual public A{              class C : virtual public A{
}                                                                 }      
EXAMPLE IN NEXT TUT*/