//LEARNT ABOUT TEMPLATES IN CPP IS AN IMPORTANT TOPIC IN VIEW OF CODE REUSE(DRY) AND COMPETITIVE PROGRAMMING
//REFER THE IMAGES OR VIDEO FOR REVISION:- https://youtu.be/kKJeekDKU30?si=ihxqzBs0k4vBdZoq
/*A CLASS IS A TEMPLATE FOR THE OBJECTS AND WE CAN CREATE TEMPLATES FOR THE CLASSES,TO GET
OTHER CLASSES OF DIFF DTATA TYPES FOLLOWING THE SAME STRUCTURE*/